---
#      author: Mark Lowcher F5 Networks
#      description: This playbook will create a clientssl profiles. It takes the clientssl
#      profile name, certificate and key from the .csv located in ./files/
#      You must first use the push_cert_key playbook to push the PEM certificate and key
#      files to the desired F5 first. You can create multiple clientssl profiles at once
#      by creating a new row in the .csv file and setting the "primary" column to "yes" 

- hosts: 10.1.1.10
  connection: local
  gather_facts: no

- name: Create clientssl profiles
  icontrol_install_config: 
    method: "_post_"
    uri: "/mgmt/tm/ltm/profile/client-ssl"
    body: '{"name":"{{profile_name}}","cert":"{{cert_name}}","key":"{{key_name}}"}'
    host: "{{bigip}}"
    username: "{{username}}"
    password: "{{password}}"

