---
- hosts: all
  connection: local
  gather_facts: no

  tasks:

   - name: Create a client SSL profile with a cert/key/specific ciphers
     bigip_profile_client_ssl:
      state: present
      server: "{{bigip}}"
      user: "{{username}}"
      password: "{{password}}"
      ciphers: "!SSLv3:!SSLv2:ECDHE+AES-GCM+SHA256:ECDHE-RSA-AES128-CBC-SHA"
      name: "{{profile_name}}"
      validate_certs: False
      cert_key_chain:
       - cert: "{{cert_name}}"
         key: "{{key_name}}"
     delegate_to: localhost
