---
- hosts: all
  connection: local
  gather_facts: no

  tasks:

   - name: Create a client SSL profile with a cert/key/specific ciphers
     bigip_profile_client_ssl:
      state: present
      server: "{{bigip}}"
      user: "{{username}}"
      password: "{{password}}"
      ciphers: "!SSLv3:!SSLv2:ECDHE+AES-GCM+SHA256:ECDHE-RSA-AES128-CBC-SHA"
      name: "{{cert_key_name}}"
      cert_key_chain:
       - cert: kenkar2.crt
         key: kenkar2.key
     delegate_to: localhost
