#!/usr/bin/ansible-playbook
---
#
#      Copyright (c) 2016 F5 Networks 
#      All rights reserved. 
#
#      --NOTICE-- This is currently not working due to a bug. It will be fixed
#      in Ansible v2.4.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will create a clientssl profile.
#      You must first use the push_cert_key_to_F5 playbook to push the certificate and key
#      files to the desired F5 first. 
#      Change the variables accordingly.
#      :%s/kenyon2/new_name/g 

- name: F5 Setup
  hosts: 10.0.0.180
  connection: local
  gather_facts: no
  vars:
    setup_user: "admin"
    setup_pass: "admin"
    bigip: "10.0.0.180"
    crt: "kenyon2"
    key: "kenyon2" 
    clientssl: "kenyon2_clientssl"
    
  tasks:

   - name: Create clientssl profiles
     icontrol_install_config: 
       method: "_post_"
       uri: "/mgmt/tm/ltm/profile/client-ssl"
       body: '{"name":"{{clientssl}}","cert":"{{crt}}","key":"{{key}}"}'
       host: "{{bigip}}"
       username: "{{setup_user}}"
       password: "{{setup_pass}}"

