---
  - hosts: bigip
    gather_facts: no

    tasks:
      - name: Reset the BIG-IP configuration, for example, to RMA the device
        bigip_config:
         reset: yes
         save: yes
#         password: "admin"
#         user: "admin"
         validate_certs: "no"
        delegate_to: localhost
