---
- hosts: all
  connection: local
  gather_facts: no

  tasks:

   - name: Resetting to default config
     bigip_command:
      state: present
      server: "{{bigip}}"
      user: "{{username}}"
      password: "{{password}}"
      command:
      - load sys config default 
     delegate_to: localhost
