---
- hosts: all
  connection: local
  gather_facts: no

  tasks:

    - name: Upload iApp template to BIG-IP
      bigip_iapp_template:
        server: "{{bigip}}"
        user: "{{username}}"
        password: "{{password}}"
        content: "{{ lookup('file', 'appsvcs_integration_v2.0.004_test.tmpl') }}"
        state: "present"
        validate_certs: False
      delegate_to: localhost

    - name: Deploy iApp
      bigip_iapp_service:
        name: "cust1-waf"
        template: "appsvcs_integration_v2.0.004_test"
        parameters: "{{ lookup('file', 'waf_final.json') }}"
        server: "{{bigip}}"
        user: "{{username}}"
        password: "{{password}}"
        state: "present"
        validate_certs: False
      delegate_to: localhost
