---
- hosts: 10.1.1.10
  connection: local
  gather_facts: no

#Upload the iApp templated downloaded above to the BIG-IP
- name: Upload iApp template to BIG-IP
  bigip_iapp_template:
    server: "{{server}}"
    user: "{{username}}"
    password: "{{password}}"
    content: "{{ lookup('file', '/var/tmp/appsvcs_integration_v2.0.004_test.tmpl') }}"
    state: "present"
    validate_certs: False
  delegate_to: localhost

#The body of the iApp is passed in as a JSON blob.
- name: Deploy iApp
  bigip_iapp_service:
    name: "cust1-waf"
    template: "appsvcs_integration_v2.0.004_test"
    parameters: "{{ lookup('file', 'waf_final.json') }}"
    server: "{{inventory}}"
    user: "{{username}}"
    password: "{{password}}"
    state: "present"
  delegate_to: localhost
