---
#
#      Copyright (c) 2016 F5 Networks
#      All rights reserved.
#
#      author: Mark Lowcher F5 Networks
#      description: This playbook will create an HA configuration
#      on two newly licensed devices.
#

- name: Set up a BIG-IP HA pair
  hosts: localhost
  gather_facts: false
  vars_files:
   - var-HA.yml

  tasks:

  - name: Change device name of BIGIP1
    bigip_hostname:
     hostname: "{{ bigip1_new_name }}"
     user: "{{ username }}"
     password: "{{ password }}"
     server: "{{ bigip1 }}"
    delegate_to: localhost

  - name: Change device name of BIGIP2
    bigip_hostname:
     hostname: "{{ bigip2_new_name }}"
     user: "{{ username }}"
     password: "{{ password }}"
     server: "{{ bigip2 }}"
    delegate_to: localhost

  - name: Disabling the setup utility device 1
    bigip_sys_global:
     gui_setup: "disabled"
     server: "{{ bigip1 }}"
     user: "{{ username }}"
     password: "{{ password }}"
     validate_certs: no
     state: present
    delegate_to: localhost

  - name: Disabling the setup utility device 2
    bigip_sys_global:
     gui_setup: "disabled"
     server: "{{ bigip2 }}"
     user: "{{ username }}"
     password: "{{ password }}"
     validate_certs: no
     state: present
    delegate_to: localhost

  - name: Creating vlans on device 1 and attaching to proper interface
    bigip_vlan:
     name: "{{ item.name }}"
     server: "{{ bigip1 }}"
     user: "{{ username }}"
     password: "{{ password }}"
     tag: "{{ item.tag }}"
     untagged_interfaces: "{{ item.interface }}"
     validate_certs: no
    with_items: "{{ vlan_information }}"
    delegate_to: localhost

  - name: Creating vlans on device 2 and attaching to proper interface
    bigip_vlan:
     name: "{{ item.name }}"
     server: "{{ bigip2 }}"
     user: "{{ username }}"
     password: "{{ password }}"
     tag: "{{ item.tag }}"
     untagged_interfaces: "{{ item.interface }}"
     validate_certs: no
    with_items: "{{ vlan_information }}"
    delegate_to: localhost

  - name: Adding self ips on device 1
    bigip_selfip:
     server: "{{ bigip1 }}"
     user: "{{ username }}"
     pass: "{{ password }}"
     name: "{{ item.name }}"
     address: "{{ item.address }}"
     vlan: "{{ item.vlan }}"
     traffic_group: "traffic-group-local-only"
     netmask: "{{ item.netmask }}"
    with_items: "{{ selfip_information1 }}"
    delegate_to: localhost

  - name: Adding self ips on device 2
    bigip_selfip:
     server: "{{ bigip2 }}"
     user: "{{ username }}"
     pass: "{{ password }}"
     name: "{{ item.name }}"
     address: "{{ item.address }}"
     vlan: "{{ item.vlan }}"
     traffic_group: "traffic-group-local-only"
     netmask: "{{ item.netmask }}"
     validate_certs: no
    with_items: "{{ selfip_information2 }}"
    delegate_to: localhost

  - name: Adding floating self ips on device 1
    bigip_selfip:
     name: "{{ item.name }}"
     server: "{{ bigip1 }}"
     user: "{{ username }}"
     pass: "{{ password }}"
     address: "{{ item.address }}"
     vlan: "{{ item.vlan }}"
     traffic_group: "traffic-group-1"
     netmask: "{{ item.netmask }}"
     validate_certs: no
    with_items: "{{ floating_self_information }}"
    delegate_to: localhost

  - name: Adding floating self ips on device 2
    bigip_selfip:
     name: "{{ item.name }}"
     server: "{{ bigip2 }}"
     user: "{{ username }}"
     pass: "{{ password }}"
     address: "{{ item.address }}"
     vlan: "{{ item.vlan }}"
     traffic_group: "traffic-group-1"
     netmask: "{{ item.netmask }}"
     validate_certs: no
    with_items: "{{ floating_self_information }}"
    delegate_to: localhost

  - name: Manage SSHD setting on BIG-IP1
    bigip_device_sshd:
     server: "{{ bigip1 }}"
     user: "{{ username }}"
     password: "{{ password }}"
     banner: "enabled"
     state: present
     banner_text: "{{ banner_text }}"
     validate_certs: no
    delegate_to: localhost

  - name: Manage SSHD setting on BIG-IP2
    bigip_device_sshd:
     server: "{{ bigip2 }}"
     user: "{{ username }}"
     password: "{{ password }}"
     banner: "enabled"
     state: present
     banner_text: "{{ banner_text }}"
     validate_certs: no
    delegate_to: localhost


#  - name: Configuring DNS servers on device 1
#    bigip_device_dns:
#     name_servers: "{{ dns_servers }}"
#     search: "{{ dns_search_domains }}"
#     state: present
#     server: "{{ bigip1 }}"
#     user: "{{ username }}"
#     password: "{{ password }}"
#     validate_certs: no
#    delegate_to: localhost

#  - name: Configuring DNS servers on device 2
#    bigip_device_dns:
#     name_servers: "{{ dns_servers }}"
#     search: "{{ dns_search_domains }}"
#     state: present
#     server: "{{ bigip2 }}"
#     user: "{{ username }}"
#     password: "{{ password }}"
#     validate_certs: no
#    delegate_to: localhost

  - name: Configuring NTP servers on device 1
    bigip_device_ntp:
     ntp_servers: "{{ ntp_servers }}"
     timezone: "{{ timezone }}"
     server: "{{ bigip1 }}"
     user: "{{ username }}"
     pass: "{{ password }}"
     state: present
     validate_certs: no
    delegate_to: localhost

  - name: Configuring NTP servers on device 2
    bigip_device_ntp:
     ntp_servers: "{{ ntp_servers }}"
     timezone: "{{ timezone }}"
     server: "{{ bigip2 }}"
     user: "{{ username }}"
     pass: "{{ password }}"
     state: present
     validate_certs: no
    delegate_to: localhost

  - name: Configure device connectivity for standard HA pair (device1)
    bigip_device_connectivity:
     config_sync_ip: "{{ha_self1}}"
     mirror_primary_address: "{{ha_self1}}"
     unicast_failover:
       - address: "{{ha_self1}}"
       - address: "{{bigip1}}"
     server: "{{bigip1}}"
     user: "{{username}}"
     password: "{{password}}"
    delegate_to: localhost

  - name: Configure device connectivity for standard HA pair (device2)
    bigip_device_connectivity:
     config_sync_ip: "{{ha_self2}}"
     mirror_primary_address: "{{ha_self2}}"
     unicast_failover:
       - address: "{{ha_self2}}"
       - address: "{{bigip2}}"
     server: "{{bigip2}}"
     user: "{{username}}"
     password: "{{password}}"
    delegate_to: localhost

  - name: Discover device for trust on BIGIP1
    bigip_command:
     server: "{{ bigip1 }}"
     user: "{{ username }}"
     password: "{{ password }}"
     commands:
     - modify cm trust-domain Root ca-devices add { "{{ bigip2 }}" } name "{{ bigip2_new_name }}" username "{{ username }}" password "{{ password }}"
    delegate_to: localhost

  - name: Create device group of type sync-failover
    bigip_command:
     server: "{{ bigip1 }}"
     user: "{{ username }}"
     password: "{{ password }}"
     commands:
      - create cm device-group sync-fail devices add { "{{ bigip1_new_name }}" "{{ bigip2_new_name }}" } type sync-failover network-failover enabled
    delegate_to: localhost

  - name: Perform initial sync of device-group
    bigip_configsync_actions:
     server: "{{ bigip1 }}"
     user: "{{ username }}"
     password: "{{ password }}"
     device_group: "sync-fail"
     sync_device_to_group: yes
     validate_certs: no
    delegate_to: localhost

  - name: Confirm HA pair is formed
    bigip_command:
     server: "{{ bigip1 }}"
     user: "{{ username }}"
     password: "{{ password }}"
     commands:
      - show cm sync-status
     wait_for:
      - result[0] contains "high-availability"
    delegate_to: localhost

  - name: Check sync and failover status of BIGIP1
    bigip_command:
     server: "{{ bigip1 }}"
     user: "{{ username }}"
     password: "{{ password }}"
     commands:
      - show cm sync-status
     wait_for:
      - result[0] contains "green"
     match: all
    delegate_to: localhost

