---
- hosts: bigip
  connection: local
  gather_facts: no

  tasks:

   - name: Pushing the certificate and key to the F5
     bigip_ssl_certificate:
       state: "present"
       server: "{{bigip}}"
       user: "{{username}}"
       password: "{{password}}"
       name: "profile_name"
       cert_src: "cert_name"
       key_src: "key_name"
       validate_certs: "no"
     delegate_to: localhost
